### ISSUE TITLE
test: documentation

### ISSUE THREAD

**Issue by Kropanov** [sergei-nntu/orb#123]
You have to go through all files into the `docs` directory and repeat instructions step by step. If you find drawbacks in the documentation files - attach here and it'll be fixed.

**Comment by Dmitriy8998** [comment]
All files in a given directory were viewed, and programs were launched both locally and with Docker. Wired testing was carried out on an empty Ubuntu 20.04 distribution.

ORM-ROS:

![Image](https://github.com/sergei-nntu/orb/assets/163279767/30abb3af-c630-452b-9ace-7914ff79725b)

Perhaps it should be said that you need to run it from the catkin_ws folder and do it only once.

**Comment by Dmitriy8998** [comment]
ORM:



![Image](https://github.com/sergei-nntu/orb/assets/163279767/deba1e7e-e7ec-415e-9c4a-7ebf242658c1)


May be you should add information about using ubuntu 20.04 on Mac. About the fact that on Mac the file orm_usb_controller.py does not see the arduino connected to usb. As a result, additional settings must be made on the Mac.

**Comment by Dmitriy8998** [comment]
Although node.js was mentioned earlier in the documentation, I assume it's worth adding here too.


![Image](https://github.com/sergei-nntu/orb/assets/163279767/f1bfd404-44df-48b8-a061-885a32e2350c)

**Comment by Dmitriy8998** [comment]
Docker:

It's not entirely clear here. Probably should be cd/orb/docker


![Image](https://github.com/sergei-nntu/orb/assets/163279767/8077d533-c09a-4651-b89a-3f491c0292d7)

**Comment by Kropanov** [comment]
Fixed! Well done, thank you!
