### ISSUE TITLE
Fix behavior of control interface

### ISSUE THREAD

**Issue by Kropanov** [sergei-nntu/orb#124]
Keyboard commands don't work. Please, fix it.

**Comment by Dmitriy8998** [comment]
I fixed the keyboard commands, but saw a completely new bug in the capture. RocketChat doesn't work. I showed this bug in a video on RocketChat. After moving the slider to the connection position, the grip value stops changing (remains in place). Working it...

**Comment by Kropanov** [comment]
@Dmitriy8998 Maybe, It's not a bug... I have to see that to make sure.

**Comment by Dmitriy8998** [comment]
Having suffered a little, I created a pull request. Maxim, please check it out. I'm afraid to press too much...
![Снимок экрана от 2024-05-22 11-54-57](https://github.com/sergei-nntu/orb/assets/163279767/002b8a9c-b36b-4c77-bc17-289993676b45)

**Comment by Kropanov** [comment]
@Dmitriy8998 Everything is good! But there is one a drawback... you shouldn't put package-lock.json to .gitignore in the `web` dir.
Can you fix it, please?

**Comment by Dmitriy8998** [comment]
I push the second commit with all the changes. Maxim, please check it out. I think that this code can be optimized even more.
