### ISSUE TITLE
key in npm install

### ISSUE THREAD

**Issue by sw1pr0g** [sergei-nntu/orb#125]
Maybe we need to update doc and replace `npm install` with npm install `--legacy-peer-deps` for the application to work correctly, because when i downloading all modules it drop me a lot of errors.
<img width="719" alt="Screenshot 2024-05-21 at 2 49 53 PM" src="https://github.com/sergei-nntu/orb/assets/80714499/02674129-a3f2-4b33-8fca-7dc1e47f4033">

**Comment by Kropanov** [comment]
@sw1pr0g Something strange, what is a branch?

**Comment by Kropanov** [comment]
![image](https://github.com/sergei-nntu/orb/assets/94756270/06685ef4-060e-4702-bb59-5dfa8accee40)

**Comment by sw1pr0g** [comment]
> @sw1pr0g Something strange, what is a branch?

develop branch, on macOS it's working but not on Ubuntu 20.04

**Comment by Kropanov** [comment]
@sw1pr0g Firstly always npm-force-resolutions should be running. Remove node_modules and package-lock.json and try that again.

**Comment by sw1pr0g** [comment]
@Kropanov I found out what the problem is - net-tools are required to work correctly on Linux. Specifically on Ubuntu, they can be installed with the command sudo apt install net-tools. After installation everything works as it should.
