### ISSUE TITLE
Joint's fields aren't working correctly

### ISSUE THREAD

**Issue by Kropanov** [sergei-nntu/orb#127]
![Image](https://github.com/sergei-nntu/orb/assets/94756270/78c4d830-117c-4203-acc4-1b1cf33c120e)
![Image](https://github.com/sergei-nntu/orb/assets/94756270/ef3d4d13-3e9b-4e28-b92a-f254ba2cb71b)

If you click on arrows of joint fields, Joint value also should be changed and we can see it on the robot 3d model.
But in practice, we've not seen this on the robot model.

**Comment by Dmitriy8998** [comment]
I tried to fix this bug. Please check it out.
