### ISSUE TITLE
App not working in Docker on MacOS

### ISSUE THREAD

**Issue by sw1pr0g** [sergei-nntu/orb#133]
I tried to launch this app with docker images. With command `docker build . -t telemetrybalkan/orb && cd .. && cd docker && docker build . -t telemetrybalkan/ros && docker compose up` and it dropped me 2 mistakes. 

<img width="570" alt="Screenshot 2024-06-05 at 10 39 08 PM" src="https://github.com/sergei-nntu/orb/assets/80714499/5cfb3be7-7a63-4324-a4f6-d44bbb3330ab">
<img width="293" alt="Screenshot 2024-06-05 at 10 38 57 PM" src="https://github.com/sergei-nntu/orb/assets/80714499/b2dc20d7-6a98-4202-8a15-61be66defd10">

On Windows with docker all works. This error only appears on MacOS.

**Comment by Kropanov** [comment]
@sw1pr0g Is it still not working?

**Comment by Kropanov** [comment]
Fixed
