### ISSUE TITLE
Fix project dependencies

### ISSUE THREAD

**Issue by Kropanov** [sergei-nntu/orb#146]

**Comment by svetlana-aristova** [comment]
An error occurs while building orb. You can see the details in the screenshots attached below.



![Image](https://github.com/sergei-nntu/orb/assets/41104090/3b588355-3b7f-4801-8e52-03687c0e0463)
![Image](https://github.com/sergei-nntu/orb/assets/41104090/4da49b95-b0a2-4fef-9355-59da58b10282)
![Image](https://github.com/sergei-nntu/orb/assets/41104090/f2c5b404-573c-4131-bbd2-01dd7d9a2ad4)
